#!/usr/bin/env bash
#
# Filename:     getRecentTraffic
#
# Description:  Get the latest traffic details for a repository in
#               which the user has admin rights. Must be authenticated.
#

# +---------------------------------------------------------------------------+
# | Set Attribute(s) for the GitHub Admin Toolkit.                            |
# | Disable this script by setting GITHUB_ADMIN_ENABLED=0                     |
# +---------------------------------------------------------------------------+
GITHUB_ADMIN_DESC="Get Recent Traffic for your org/repo. (Currently only available on github.com)"
GITHUB_ADMIN_ENABLED=1

# +---------------------------------------------------------------------------+
# | We need a minimum set of params before we can continue.                   |
# +---------------------------------------------------------------------------+

# This must only be run against github.com. See https://developer.github.com/v3/repos/traffic/
if [ "$SERVER" == "github.com" ]; then
  export APIBASE="https://api.github.com";
  [[ -n "$DEBUG" ]] && echo "APIBASE is $APIBASE";
else
  if [ -n "$SERVER" ] && [ "$SERVER" != "github.com" ]; then
    printf "\nERROR: The server for this script must be github.com while this endpoint is in Preview mode. See https://developer.github.com/v3/repos/traffic/ for details.\n\n"
    exit 1;
  fi;
fi

# Check that we have an APIBASE to connect to
if [ ! -n "$APIBASE" ]; then
  echo -n "Enter the API base url of the GitHub server (i.e. https://api.github.com) and press [ENTER]: ";
  read APIBASE;
  export APIBASE=$APIBASE;
fi;

# Check that we have an OWNER to work with
if [ ! -n "$OWNER" ]; then
  echo -n "Enter the name of the GitHub Owner and press [ENTER]: ";
  read OWNER;
  export OWNER=$OWNER;
fi

# Check that we have a AUTH token to work with
if [ ! -n "$AUTH" ]; then
  echo -n "Enter a GitHub Auth token and press [ENTER]: ";
  read AUTH;
  export AUTH=$AUTH;
fi

# +---------------------------------------------------------------------------+
# | Perform work.                                                             |
# +---------------------------------------------------------------------------+

# Call module
python ./scripts/modules/github-admin-toolkit.py getRecentTraffic
